// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "coxtv_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// fit
Rcpp::List fit(Rcpp::NumericMatrix X, Rcpp::NumericMatrix V, Rcpp::IntegerVector Vind, Rcpp::IntegerVector order, Rcpp::IntegerVector erank, Rcpp::IntegerVector eind, Rcpp::NumericVector te_count, double step_size, Rcpp::NumericVector B_init, Rcpp::NumericVector lambda_1_all, Rcpp::NumericVector penalty_factor, int niter, double linesearch_beta, double eps, double tol);
RcppExport SEXP _coxtv_fit(SEXP XSEXP, SEXP VSEXP, SEXP VindSEXP, SEXP orderSEXP, SEXP erankSEXP, SEXP eindSEXP, SEXP te_countSEXP, SEXP step_sizeSEXP, SEXP B_initSEXP, SEXP lambda_1_allSEXP, SEXP penalty_factorSEXP, SEXP niterSEXP, SEXP linesearch_betaSEXP, SEXP epsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Vind(VindSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type erank(erankSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type eind(eindSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type te_count(te_countSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_1_all(lambda_1_allSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type penalty_factor(penalty_factorSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type linesearch_beta(linesearch_betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fit(X, V, Vind, order, erank, eind, te_count, step_size, B_init, lambda_1_all, penalty_factor, niter, linesearch_beta, eps, tol));
    return rcpp_result_gen;
END_RCPP
}
// get_te_count
Rcpp::IntegerVector get_te_count(Rcpp::IntegerVector erank);
RcppExport SEXP _coxtv_get_te_count(SEXP erankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type erank(erankSEXP);
    rcpp_result_gen = Rcpp::wrap(get_te_count(erank));
    return rcpp_result_gen;
END_RCPP
}
// get_residual
Rcpp::NumericVector get_residual(Rcpp::NumericMatrix X, Rcpp::NumericMatrix V, Rcpp::IntegerVector Vind, Rcpp::IntegerVector order, Rcpp::IntegerVector erank, Rcpp::IntegerVector eind, Rcpp::NumericVector te_count, Rcpp::NumericVector beta);
RcppExport SEXP _coxtv_get_residual(SEXP XSEXP, SEXP VSEXP, SEXP VindSEXP, SEXP orderSEXP, SEXP erankSEXP, SEXP eindSEXP, SEXP te_countSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Vind(VindSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type erank(erankSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type eind(eindSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type te_count(te_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_residual(X, V, Vind, order, erank, eind, te_count, beta));
    return rcpp_result_gen;
END_RCPP
}
// CCIndex
double CCIndex(Rcpp::NumericVector eta, Rcpp::NumericVector eta_td, Rcpp::IntegerVector Vind, Rcpp::IntegerVector rank_all, Rcpp::IntegerVector erankwt, Rcpp::IntegerVector eranke, Rcpp::IntegerVector te_count);
RcppExport SEXP _coxtv_CCIndex(SEXP etaSEXP, SEXP eta_tdSEXP, SEXP VindSEXP, SEXP rank_allSEXP, SEXP erankwtSEXP, SEXP erankeSEXP, SEXP te_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_td(eta_tdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Vind(VindSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type rank_all(rank_allSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type erankwt(erankwtSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type eranke(erankeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type te_count(te_countSEXP);
    rcpp_result_gen = Rcpp::wrap(CCIndex(eta, eta_td, Vind, rank_all, erankwt, eranke, te_count));
    return rcpp_result_gen;
END_RCPP
}
// get_V
void get_V(Rcpp::NumericVector V, const Rcpp::NumericVector td_covs, const Rcpp::NumericVector td_time, const Rcpp::NumericVector etime, const Rcpp::IntegerVector cumu_measurement, const Rcpp::IntegerVector erank, const Rcpp::IntegerVector vind);
RcppExport SEXP _coxtv_get_V(SEXP VSEXP, SEXP td_covsSEXP, SEXP td_timeSEXP, SEXP etimeSEXP, SEXP cumu_measurementSEXP, SEXP erankSEXP, SEXP vindSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type td_covs(td_covsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type td_time(td_timeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type etime(etimeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type cumu_measurement(cumu_measurementSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type erank(erankSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type vind(vindSEXP);
    get_V(V, td_covs, td_time, etime, cumu_measurement, erank, vind);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coxtv_fit", (DL_FUNC) &_coxtv_fit, 15},
    {"_coxtv_get_te_count", (DL_FUNC) &_coxtv_get_te_count, 1},
    {"_coxtv_get_residual", (DL_FUNC) &_coxtv_get_residual, 8},
    {"_coxtv_CCIndex", (DL_FUNC) &_coxtv_CCIndex, 7},
    {"_coxtv_get_V", (DL_FUNC) &_coxtv_get_V, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_coxtv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
