# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit <- function(X, V, Vind, order, erank, eind, te_count, step_size, B_init, lambda_1_all, penalty_factor, niter, linesearch_beta, eps, tol = 1e-10) {
    .Call(`_coxtv_fit`, X, V, Vind, order, erank, eind, te_count, step_size, B_init, lambda_1_all, penalty_factor, niter, linesearch_beta, eps, tol)
}

get_te_count <- function(erank) {
    .Call(`_coxtv_get_te_count`, erank)
}

get_residual <- function(X, V, Vind, order, erank, eind, te_count, beta) {
    .Call(`_coxtv_get_residual`, X, V, Vind, order, erank, eind, te_count, beta)
}

CCIndex <- function(eta, eta_td, Vind, rank_all, erankwt, eranke, te_count) {
    .Call(`_coxtv_CCIndex`, eta, eta_td, Vind, rank_all, erankwt, eranke, te_count)
}

get_V <- function(V, td_covs, td_time, etime, cumu_measurement, erank, vind) {
    invisible(.Call(`_coxtv_get_V`, V, td_covs, td_time, etime, cumu_measurement, erank, vind))
}

